#include "koaloader/koaloader.hpp"

using namespace koaloader;

#if PROXY_DLL_VERSION

FUNC_IMPL(BOOL, GetFileVersionInfoA, ARGS(LPCSTR, DWORD, DWORD, LPVOID))
FUNC_IMPL(BOOL, GetFileInformationByHandle, ARGS(HANDLE, LPBY_HANDLE_FILE_INFORMATION))
FUNC_IMPL(BOOL, GetFileVersionInfoExA, ARGS(DWORD, LPCSTR, DWORD, DWORD, LPVOID))
FUNC_IMPL(BOOL, GetFileVersionInfoExW, ARGS(DWORD, LPCWSTR, DWORD, DWORD, LPVOID))
FUNC_IMPL(DWORD, GetFileVersionInfoSizeA, ARGS(LPCSTR, LPDWORD))
FUNC_IMPL(DWORD, GetFileVersionInfoSizeExA, ARGS(DWORD, LPCSTR, LPDWORD))
FUNC_IMPL(DWORD, GetFileVersionInfoSizeExW, ARGS(DWORD, LPCWSTR, LPDWORD))
FUNC_IMPL(DWORD, GetFileVersionInfoSizeW, ARGS(LPCWSTR, LPDWORD))
FUNC_IMPL(BOOL, GetFileVersionInfoW, ARGS(LPCWSTR, DWORD, DWORD, LPVOID))
FUNC_IMPL(DWORD, VerFindFileA, ARGS(DWORD, LPCSTR, LPCSTR, LPCSTR, LPSTR, PUINT, LPSTR, PUINT))
FUNC_IMPL(DWORD, VerFindFileW, ARGS(DWORD, LPCWSTR, LPCWSTR, LPCWSTR, LPWSTR, PUINT, LPWSTR, PUINT))
FUNC_IMPL(DWORD, VerInstallFileA, ARGS(DWORD, LPCSTR, LPCSTR, LPCSTR, LPCSTR, LPCSTR, LPSTR, PUINT))
FUNC_IMPL(DWORD, VerInstallFileW, ARGS(DWORD, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, LPWSTR, PUINT))
FUNC_IMPL(DWORD, VerLanguageNameA, ARGS(DWORD, LPSTR, DWORD))
FUNC_IMPL(DWORD, VerLanguageNameW, ARGS(DWORD, LPWSTR, DWORD))
FUNC_IMPL(BOOL, VerQueryValueA, ARGS(LPCVOID, LPCSTR, LPVOID * , PUINT))
FUNC_IMPL(BOOL, VerQueryValueW, ARGS(LPCVOID, LPCWSTR, LPVOID * , PUINT))

#endif
